### ISSUE TITLE
Updating to “lang-gdscript@4.0.0” failed

### ISSUE THREAD

**Issue by Volcanic-Penguin** [PrestonKnopp/language-gdscript#13]
```
> tree-sitter-gdscript@0.2.0 install C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Temp\apm-install-dir-119316-20044-1ev53fu.jg6vi\node_modules\lang-gdscript\node_modules\tree-sitter-gdscript
> node-gyp rebuild


C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Temp\apm-install-dir-119316-20044-1ev53fu.jg6vi\node_modules\lang-gdscript\node_modules\tree-sitter-gdscript>if not defined npm_config_node_gyp (node "C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\lee_c.DESKTOP-BK84R0I\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\lee_c.DESKTOP-BK84R0I\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Programs\Python\Python36-32\python.EXE
gyp verb check python version `C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Programs\Python\Python36-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.0\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\lee_c.DESKTOP-BK84R0I\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\lee_c.DESKTOP-BK84R0I\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Temp\apm-install-dir-119316-20044-1ev53fu.jg6vi\node_modules\lang-gdscript\node_modules\tree-sitter-gdscript
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\lee_c.DESKTOP-BK84R0I\AppData\Local\Temp\apm-install-dir-119316-20044-1ev53fu.jg6vi\package.json'
npm WARN apm-install-dir-119316-20044-1ev53fu.jg6vi No description
npm WARN apm-install-dir-119316-20044-1ev53fu.jg6vi No repository field.
npm WARN apm-install-dir-119316-20044-1ev53fu.jg6vi No README data
npm WARN apm-install-dir-119316-20044-1ev53fu.jg6vi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-gdscript@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-gdscript@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lee_c.DESKTOP-BK84R0I\.atom\.apm\_logs\2019-04-16T07_39_28_071Z-debug.log
```

Is the package assuming that I have python installed on my computer?

**Comment by PrestonKnopp** [comment]
Hey, this is a surprise to me. It turns out that node-gyp is a python based compilation tool. Atom uses node-gyp to compile [tree-sitter-gdscript](https://www.npmjs.com/package/tree-sitter-gdscript) for tree-sitter which is atom's new language grammar parser.

I'll do some research to see how to have tree-sitter as a dependency but fall back to textmate grammars without having npm spam errors.

For the future, I'm working on better autocompletion using the tree-sitter-gdscript parser. If you would like here's the guide on getting [window's ready for node-gyp](https://github.com/nodejs/node-gyp#on-windows).

If you want to use the previous version you can download the zip for the [](https://github.com/PrestonKnopp/language-gdscript/releases/tag/v3.7.0) and unzip into a folder of your choosing and then run `apm link` inside of the folder.

I'm sorry for the inconvenience. If there's anything that I can do in the interim let me know.

**Comment by PrestonKnopp** [comment]
Could you post the output of the command `apm --version`?

**Comment by PrestonKnopp** [comment]
I have been working on getting appveyor setup to publish prebuilt binaries for Windows and I think it's setup right. 

When you have a moment, could you try reinstalling language-gdscript from the atom editor and seeing if it installs successfully?

**Comment by jebedaia360** [comment]
I get similar result when updating form 4.1.0 to 4.1.1.
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for tree-sitter-gdscript@^0.2.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'lang-gdscript'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeremi360/.atom/.apm/_logs/2019-04-17T06_55_56_675Z-debug.log
```

**Comment by Volcanic-Penguin** [comment]
Version 4.1.1 installed successfully!

**Comment by PrestonKnopp** [comment]
Awesome. I’m going to close this issue as I think it’s resolved. Thank you!
