### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 69

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#25]
After atom update 1.41 I got this error end need to rebuild.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: [lang-gdscript](https://github.com/PrestonKnopp/language-gdscript) package 4.1.2

### Stack Trace

Failed to load a lang-gdscript package grammar

```
At The module '/home/jeremi360/.atom/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /home/jeremi360/.atom/packages/lang-gdscript/grammars/tree-sitter-gdscript.cson

Error: The module '/home/jeremi360/.atom/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:2:20)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:11:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688211)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3128927)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360047)
    at l.readFile (/usr/share/atom/resources/app/static/<embedded>:11:359888)
    at /usr/share/atom/resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/lang-gdscript/grammars/tree-sitter-gdscript.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
adventure-time-ui 0.1.0 
ambiance-dark-syntax 0.1.1 
arc-ui 0.1.7 
atom-arc-dark-ui 0.1.7 
atom-ide-terminal 5.0.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-save-all 0.4.1 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 2.0.1 
chrome-color-picker 0.8.0 
dark-python-syntax 2.3.0 
editor-background 1.2.42 
flex-tool-bar 2.1.4 
git-hide 1.0.0 
ide-json 0.2.1 
ide-python 1.5.0 
intentions 1.1.5 
lang-gdscript 4.1.2 
language-ignore 1.8.0 
language-renpy 2.5.0 
linter 2.3.1 
linter-ui-default 1.8.0 
lomokai-syntax 0.3.3 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
monokai-arc 0.31.4 
monokai-dark 1.5.0 
monokai-dave 0.2.0 
monokai-flat-ui 4.2.0 
monokai-ubuntu 0.9.0 
nordkind-dark-syntax 0.6.0 
omnisharp-atom 0.31.2 
one-dark-rainbow-syntax 1.0.0 
pigments 0.40.2 
pop-syntax 0.5.0 
pop-ui 0.6.1 
power-effects 0.5.0 
project-manager 3.3.8 
python-stero 0.2.0 
rain-syntax 2.1.2 
renpy-dark-syntax 1.2.0 
renpy-light-syntax 1.2.0 
seti-icons 1.5.4 
sync-settings 0.8.6 
tab-title 0.3.5 
tool-bar 1.2.0 
Tycho-Light-Arc-Syntax 0.1.0 
typewriter-sounds 3.0.1 
```

**Comment by PrestonKnopp** [comment]
Hey, thanks for posting an issue!

Are you able to rebuild successfully? This is actually expected behavior and normally requires a rebuild or reinstall.

Does Atom prompt you to rebuild or does it only throw this error?

**Comment by jebedaia360** [comment]
Yes rebuild successfully :smile:

**Comment by PrestonKnopp** [comment]
Awesome, thanks again jebedaia!
