### ISSUE TITLE
Failed to load a lang-gdscript package grammar

### ISSUE THREAD

**Issue by petursson1** [PrestonKnopp/language-gdscript#37]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [lang-gdscript](https://github.com/PrestonKnopp/language-gdscript) package 6.0.0

### Stack Trace

Failed to load a lang-gdscript package grammar

```
At The module '/Users/admin/.atom/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/admin/.atom/packages/lang-gdscript/grammars/tree-sitter-gdscript.json

Error: The module '/Users/admin/.atom/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:2:20)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3114911)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360436)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360277
    at u (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:580990)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:582243
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/lang-gdscript/grammars/tree-sitter-gdscript.json:1:1
```

### Commands

```
     -2:33.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
ide-python 1.5.0 
lang-gdscript 6.0.0 
pane-layout-plus 0.7.4 
script 3.26.0 
tag 0.5.0 
xml-formatter 0.13.0 
xml-tools 0.2.1 
```

**Comment by TheSHEEEP** [comment]
Same. except for me it is using version 70, but requires 73.

**Comment by magikmw** [comment]
I've had this error on a previous version, but update to 6.1.0 solved it, and the package loads without errors.

**Comment by Xqua** [comment]
Fixed by updating to 6.2.0
