### ISSUE TITLE
Unable to install lang-gdscript from atom's package install screen

### ISSUE THREAD

**Issue by karthanistyr** [PrestonKnopp/language-gdscript#42]
When trying to install lang-gdscript:
```
Installing “lang-gdscript@6.0.0” failed.Hide output…

> tree-sitter-gdscript@1.0.0 install /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript
> prebuild-install || node-gyp rebuild

make : on entre dans le répertoire « /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript/build »
  CXX(target) Release/obj.target/tree_sitter_gdscript_binding/src/scanner.o
  CC(target) Release/obj.target/tree_sitter_gdscript_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_gdscript_binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/tree_sitter_gdscript_binding.node
  COPY Release/tree_sitter_gdscript_binding.node
make : on quitte le répertoire « /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript/build »

> tree-sitter-godot-resource@0.1.0 install /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-godot-resource
> prebuild-install || node-gyp rebuild

make : on entre dans le répertoire « /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-godot-resource/build »
  CC(target) Release/obj.target/tree_sitter_godotResource_binding/src/parser.o
  CC(target) Release/obj.target/tree_sitter_godotResource_binding/src/scanner.o
  CXX(target) Release/obj.target/tree_sitter_godotResource_binding/src/binding.o
make : on quitte le répertoire « /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-godot-resource/build »

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=linux)
Dans le fichier inclus depuis ../src/parser.c:1:
../src/parser.c: Dans la fonction « ts_lex_keywords »:
../src/tree_sitter/parser.h:127:8: attention: variable « eof » définie mais non utilisée [-Wunused-but-set-variable]
  127 |   bool eof = false;             \
      |        ^~~
../src/parser.c:1911:3: note: dans l'expansion de la macro « START_LEXER »
 1911 |   START_LEXER();
      |   ^~~~~~~~~~~
Dans le fichier inclus depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8-internal.h:14,
                 depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:25,
                 depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:63,
                 depuis ../src/binding.cc:2:
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:49: attention: « v8::MicrotasksCompletedCallback » est obsolète: Use *WithData version. [-Wdeprecated-declarations]
  326 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:8205:3: note: dans l'expansion de la macro « V8_DEPRECATE_SOON »
 8205 |   V8_DEPRECATE_SOON("Use *WithData version.",
      |   ^~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:6668:34: note: déclaré ici
 6668 |                   typedef void (*MicrotasksCompletedCallback)(Isolate*));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:3: note: dans la définition de la macro « V8_DEPRECATE_SOON »
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:49: attention: « v8::MicrotasksCompletedCallback » est obsolète: Use *WithData version. [-Wdeprecated-declarations]
  326 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:8214:3: note: dans l'expansion de la macro « V8_DEPRECATE_SOON »
 8214 |   V8_DEPRECATE_SOON("Use *WithData version.",
      |   ^~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:6668:34: note: déclaré ici
 6668 |                   typedef void (*MicrotasksCompletedCallback)(Isolate*));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:3: note: dans la définition de la macro « V8_DEPRECATE_SOON »
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
Dans le fichier inclus depuis ../src/binding.cc:2:
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:572:7: attention: transtypage entre types de fonctions incompatibles de « void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>) » vers « node::addon_register_func » {aka « void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*) »} [-Wcast-function-type]
  572 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:606:3: note: dans l'expansion de la macro « NODE_MODULE_X »
  606 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cc:26:1: note: dans l'expansion de la macro « NODE_MODULE »
   26 | NODE_MODULE(tree_sitter_gdscript_binding, Init)
      | ^~~~~~~~~~~
Dans le fichier inclus depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:63,
                 depuis ../src/binding.cc:2:
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h: Dans l'instanciation de « void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)] » :
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node_object_wrap.h:84:78:   requis depuis ici
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:9810:16: attention: transtypage entre types de fonctions incompatibles de « v8::WeakCallbackInfo<node::ObjectWrap>::Callback » {aka « void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&) »} vers « Callback » {aka « void (*)(const v8::WeakCallbackInfo<void>&) »} [-Wcast-function-type]
 9810 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h: Dans l'instanciation de « void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)] » :
../../nan/nan_object_wrap.h:65:61:   requis depuis ici
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:9810:16: attention: transtypage entre types de fonctions incompatibles de « v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback » {aka « void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&) »} vers « Callback » {aka « void (*)(const v8::WeakCallbackInfo<void>&) »} [-Wcast-function-type]
prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=linux)
Dans le fichier inclus depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8-internal.h:14,
                 depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:25,
                 depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:63,
                 depuis ../src/binding.cc:2:
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:49: attention: « v8::MicrotasksCompletedCallback » est obsolète: Use *WithData version. [-Wdeprecated-declarations]
  326 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:8205:3: note: dans l'expansion de la macro « V8_DEPRECATE_SOON »
 8205 |   V8_DEPRECATE_SOON("Use *WithData version.",
      |   ^~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:6668:34: note: déclaré ici
 6668 |                   typedef void (*MicrotasksCompletedCallback)(Isolate*));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:3: note: dans la définition de la macro « V8_DEPRECATE_SOON »
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:49: attention: « v8::MicrotasksCompletedCallback » est obsolète: Use *WithData version. [-Wdeprecated-declarations]
  326 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:8214:3: note: dans l'expansion de la macro « V8_DEPRECATE_SOON »
 8214 |   V8_DEPRECATE_SOON("Use *WithData version.",
      |   ^~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:6668:34: note: déclaré ici
 6668 |                   typedef void (*MicrotasksCompletedCallback)(Isolate*));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8config.h:326:3: note: dans la définition de la macro « V8_DEPRECATE_SOON »
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/binding.cc:13:6: erreur: variable ou champ « Init » déclaré « void »
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |      ^~~~
../src/binding.cc:13:11: erreur: « Handle » n'a pas été déclaré dans cette portée
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |           ^~~~~~
../src/binding.cc:13:24: erreur: expected primary-expression before « > » token
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |                        ^
../src/binding.cc:13:26: erreur: « exports » n'a pas été déclaré dans cette portée
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |                          ^~~~~~~
../src/binding.cc:13:35: erreur: « Handle » n'a pas été déclaré dans cette portée
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |                                   ^~~~~~
../src/binding.cc:13:48: erreur: expected primary-expression before « > » token
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |                                                ^
../src/binding.cc:13:50: erreur: « module » n'a pas été déclaré dans cette portée
   13 | void Init(Handle<Object> exports, Handle<Object> module) {
      |                                                  ^~~~~~
Dans le fichier inclus depuis ../src/binding.cc:2:
../src/binding.cc:26:48: erreur: « Init » n'a pas été déclaré dans cette portée; vouliez-vous employer « node::Init » ?
   26 | NODE_MODULE(tree_sitter_godotResource_binding, Init)
      |                                                ^~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:572:36: note: dans la définition de la macro « NODE_MODULE_X »
  572 |       (node::addon_register_func) (regfunc),                          \
      |                                    ^~~~~~~
../src/binding.cc:26:1: note: dans l'expansion de la macro « NODE_MODULE »
   26 | NODE_MODULE(tree_sitter_godotResource_binding, Init)
      | ^~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:221:18: note: « node::Init » déclaré ici
  221 | NODE_EXTERN void Init(int* argc,
      |                  ^~~~
Dans le fichier inclus depuis /home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node.h:63,
                 depuis ../src/binding.cc:2:
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h: Dans l'instanciation de « void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)] » :
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/node_object_wrap.h:84:78:   requis depuis ici
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:9810:16: attention: transtypage entre types de fonctions incompatibles de « v8::WeakCallbackInfo<node::ObjectWrap>::Callback » {aka « void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&) »} vers « Callback » {aka « void (*)(const v8::WeakCallbackInfo<void>&) »} [-Wcast-function-type]
 9810 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h: Dans l'instanciation de « void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)] » :
../../nan/nan_object_wrap.h:65:61:   requis depuis ici
/home/karthanis/.atom/.node-gyp/.cache/node-gyp/6.1.12/include/node/v8.h:9810:16: attention: transtypage entre types de fonctions incompatibles de « v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback » {aka « void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&) »} vers « Callback » {aka « void (*)(const v8::WeakCallbackInfo<void>&) »} [-Wcast-function-type]
Dans le fichier inclus depuis ../src/binding.cc:3:
../src/binding.cc:11:12: attention: « Nan::NAN_METHOD_RETURN_TYPE {anonymous}::New(Nan::NAN_METHOD_ARGS_TYPE) » défini mais pas utilisé [-Wunused-function]
   11 | NAN_METHOD(New) {}
      |            ^~~
../../nan/nan.h:1568:33: note: dans la définition de la macro « NAN_METHOD »
 1568 |     Nan::NAN_METHOD_RETURN_TYPE name(Nan::NAN_METHOD_ARGS_TYPE info)
      |                                 ^~~~
make: *** [tree_sitter_godotResource_binding.target.mk:111 : Release/obj.target/tree_sitter_godotResource_binding/src/binding.o] Erreur 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.9.1-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/node_modules/lang-gdscript/node_modules/tree-sitter-godot-resource
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2020926-537794-g48d7u.k3ujo/package.json'
npm WARN apm-install-dir-2020926-537794-g48d7u.k3ujo No description
npm WARN apm-install-dir-2020926-537794-g48d7u.k3ujo No repository field.
npm WARN apm-install-dir-2020926-537794-g48d7u.k3ujo No README data
npm WARN apm-install-dir-2020926-537794-g48d7u.k3ujo No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-godot-resource@0.1.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-godot-resource@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/karthanis/.atom/.apm/_logs/2020-10-26T15_33_56_999Z-debug.log
```

**Comment by karthanistyr** [comment]
Ah man, you essentially fixed this issue already in PrestonKnopp/tree-sitter-godot-resource -- the released version on npm can't build on more modern node (I run node 15), but by using HEAD it does build.

I could install language-gdscript by simply using HEAD of the tree-sitter-godot-resource dep.

Would you consider doing a release cycle to fix the addon in the atom package manager?

**Comment by xhokir** [comment]
I have the exact same issue here. @karthanistyr how did you manage to use the HEAD of tree-sitter-godot-resource during lang-gdscript install ?

I tried installing tree-sitter-godot-resource through npm (by `npm install tree-sitter-godot-resource`) beforhands. It succeeded but did not change the error I get while `apm install lang-gdscript`

Using : 
node 10.19.0
atom 1.53.0

**Comment by karthanistyr** [comment]
@Xhokir You would need to modify package.json and replace the version spec for tree-sitter-godot-resource

Where it says ˋ^0.1.0` you would put ˋPrestonKopp/tree-sitter-godot-resourceˋ

and the you follow the manual installation instructions (basically ˋapm install` followed by ˋapm link`

No need to deal with tree-sitter-godot-resource manually

**Comment by PrestonKnopp** [comment]
@karthanistyr Hi, thanks for raising an issue, I apologize for the untimely response and inconvenience. 

I have updated the dependencies and published a new version of the package to apm. Try a clean install and let me know if there are any issues.

**Comment by xhokir** [comment]
Thanks a lot @karthanistyr for your advice !

@PrestonKnopp thanks also for the new realease: it solved the issue for me and I was able to install the atom plugin without problem.

**Comment by karthanistyr** [comment]
@PrestonKnopp no worries at all
the new update looks to work fine on my end, thank you!
