### ISSUE TITLE
can't install lang-gdscript 6.2.0

### ISSUE THREAD

**Issue by ShivaPrakash-006** [PrestonKnopp/language-gdscript#49]
tried to install lang-gdscript from atom but i am getting this error message:

> zadeh@3.0.0-beta.4 install C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\node_modules\lang-gdscript\node_modules\zadeh
> node-gyp-build

> tree-sitter-gdscript@1.2.1 install C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\node_modules\lang-gdscript\node_modules\tree-sitter-gdscript
> prebuild-install || node-gyp rebuild

> tree-sitter-godot-resource@0.2.1 install C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\node_modules\lang-gdscript\node_modules\tree-sitter-godot-resource
> prebuild-install || node-gyp rebuild

C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\node_modules\lang-gdscript\node_modules\tree-sitter-godot-resource>if not defined npm_config_node_gyp (node "C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=9.4.4 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.11.31702.278) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Shiva Prakash\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\Shiva Prakash\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Shiva Prakash\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\node_modules\lang-gdscript\node_modules\tree-sitter-godot-resource
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\SHIVAP~1\AppData\Local\Temp\apm-install-dir-20211112-10892-1dlskj6.bzyz\package.json'
npm WARN apm-install-dir-20211112-10892-1dlskj6.bzyz No description
npm WARN apm-install-dir-20211112-10892-1dlskj6.bzyz No repository field.
npm WARN apm-install-dir-20211112-10892-1dlskj6.bzyz No README data
npm WARN apm-install-dir-20211112-10892-1dlskj6.bzyz No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-godot-resource@0.2.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-godot-resource@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shiva Prakash\.atom\.apm\_logs\2021-12-12T02_34_56_244Z-debug.log

**Comment by ShivaPrakash-006** [comment]
I tried all the comments given in issue #48 , but this still appears
